### ISSUE TITLE
optimization suggestion

### ISSUE THREAD

**Issue by jerryfischer** [emmt/NumOptBase.jl#1]
Very nice work !
I wondered if you have considered rewriting another version in Python ? Since it is de-facto _the_ programming language when speed is a requirement. I mean, Julia is fine but Python is rock-solid:  fast, and _business-safe_.
Looking forward for updates 😁

**Comment by emmt** [comment]
Thank you for your comments. I have not yet planned to port this to Python. You may have a look at https://github.com/emmt/VMLMB/tree/main/python which is an implementation of my VMLMB algorithm in pure Python and with a similar API for vector-like computations.
